# Generated by Django 5.1.7 on 2025-05-22 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_profile_image',
            field=models.URLField(blank=True, default='', max_length=255, null=True),
        ),
    ]
