# Generated by Django 5.2 on 2025-05-12 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_add_max_products'),
        ('companies', '0002_update_subscription_plans'),
        ('companies', '0003_alter_company_options_remove_company_address_and_more'),
    ]

    operations = [
    ]
