# Generated by Django 5.1.7 on 2025-05-05 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_purchase_price_product_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='is_active',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
    ]
