# Generated by Django 5.2 on 2025-05-21 10:38

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('SALES', 'Sales Report'), ('INVENTORY', 'Inventory Report'), ('FINANCIAL', 'Financial Report'), ('CUSTOMER', 'Customer Report'), ('PRODUCT', 'Product Performance Report'), ('PROFIT', 'Profit Report'), ('REVENUE', 'Revenue Report')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('date_range_start', models.DateTimeField()),
                ('date_range_end', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.store')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerReport',
            fields=[
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='reports.report')),
                ('total_customers', models.IntegerField(default=0)),
                ('new_customers', models.IntegerField(default=0)),
                ('returning_customers', models.IntegerField(default=0)),
                ('top_customers', models.JSONField(default=dict)),
                ('average_purchase_value', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=19)),
                ('customer_retention_rate', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='reports.report')),
                ('total_sales', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=19)),
                ('total_expenses', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=19)),
                ('total_purchases', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=19)),
                ('total_payment_ins', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=19)),
                ('total_payment_outs', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=19)),
                ('gross_profit', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=19)),
                ('net_profit', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=19)),
                ('profit_margin_percentage', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10)),
                ('expense_breakdown', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryReport',
            fields=[
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='reports.report')),
                ('total_products', models.IntegerField(default=0)),
                ('low_stock_products', models.JSONField(default=dict)),
                ('out_of_stock_products', models.JSONField(default=dict)),
                ('overstocked_products', models.JSONField(default=dict)),
                ('inventory_value', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=19)),
                ('inventory_turnover_rate', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProductPerformanceReport',
            fields=[
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='reports.report')),
                ('top_performing_products', models.JSONField(default=dict)),
                ('worst_performing_products', models.JSONField(default=dict)),
                ('product_category_breakdown', models.JSONField(default=dict)),
                ('seasonal_product_trends', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='ProfitReport',
            fields=[
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='reports.report')),
                ('gross_profit', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=19)),
                ('net_profit', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=19)),
                ('profit_margin_percentage', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10)),
                ('sales_revenue', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=19)),
                ('cost_of_goods_sold', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=19)),
                ('operating_expenses', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=19)),
                ('profit_by_product_category', models.JSONField(default=dict)),
                ('profit_trend', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='RevenueReport',
            fields=[
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='reports.report')),
                ('total_revenue', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=19)),
                ('sales_revenue', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=19)),
                ('other_revenue', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=19)),
                ('revenue_by_payment_mode', models.JSONField(default=dict)),
                ('revenue_by_product_category', models.JSONField(default=dict)),
                ('daily_revenue', models.JSONField(default=dict)),
                ('monthly_revenue', models.JSONField(default=dict)),
                ('average_daily_revenue', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=19)),
            ],
        ),
        migrations.CreateModel(
            name='SalesReport',
            fields=[
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='reports.report')),
                ('total_sales', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=19)),
                ('total_items_sold', models.IntegerField(default=0)),
                ('average_sale_value', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=19)),
                ('highest_sale_value', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=19)),
                ('total_credit_sales', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=19)),
                ('total_cash_sales', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=19)),
                ('top_selling_products', models.JSONField(default=dict)),
                ('daily_sales_breakdown', models.JSONField(default=dict)),
            ],
        ),
    ]
