# Generated by Django 5.1.7 on 2025-05-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmode',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
