# Generated by Django 5.1.7 on 2025-05-22 00:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='tax',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=19),
        ),
        migrations.AddField(
            model_name='sale',
            name='tax',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=19),
        ),
    ]
