# Generated by Django 5.1.7 on 2025-05-18 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothings', '0002_alter_color_store_id'),
        ('companies', '0002_alter_currency_code_alter_currency_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='store_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.store'),
        ),
    ]
